insert into locations values('Bloomington',1,'IN','city','Bloomington');
insert into locations values('Bloomington',2,'IN','attraction','Indiana University');
insert into locations values('Bloomington',3,'IN','hotel','Super 8 by Wyndam');
insert into locations values('Bloomington',4,'IN','restaurant','Taste of India');
insert into locations values('Chicago',5,'IL','city','Chicago');
insert into locations values('Chicago',6,'IL','attraction','Chicago Pier');
insert into locations values('Chicago',7,'IL','hotel','Homewood Suites');
insert into locations values('Chicago',8,'IL','restaurant','Bryanna''s Restaurant');
insert into locations values('Detroit',9,'MI','city','Detroit');
insert into locations values('Detroit',10,'MI','attraction','Detroit Institute of Arts');
insert into locations values('Detroit',11,'MI','restaurant','Dilla''s Delights');
insert into locations values('Detroit',12,'MI','hotel','MotorCity Casino Hotel');
insert into locations values('Los Angeles',13,'CA','city','Los Angeles');
insert into locations values('Los Angeles',14,'CA','attraction','Venice Beach');
insert into locations values('Los Angeles',15,'CA','hotel','Hotel Indigo Los Angeles Downtown');
insert into locations values('Los Angeles',16,'CA','restaurant','San Pedro Fish Market & Restaurant');
