insert into locations values('Bloomington',1,'IN','city','Bloomington','https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Bloomington_IN_Kirkwood.jpg/1920px-Bloomington_IN_Kirkwood.jpg');
insert into locations values('Bloomington',2,'IN','attraction','Indiana University','https://static.independent.co.uk/s3fs-public/thumbnails/image/2016/08/19/12/indiana-university.jpg');
insert into locations values('Bloomington',3,'IN','hotel','Super 8 by Wyndam','https://edge.media.datahc.com/HI371739098.jpg');
insert into locations values('Bloomington',4,'IN','restaurant','Taste of India','http://www.tasteofindiabtown.com/images/photo_inside2.jpg');
insert into locations values('Chicago',5,'IL','city','Chicago','https://www.moneycrashers.com/wp-content/uploads/2019/03/visit-chicago-attractions-places.jpg');
insert into locations values('Chicago',6,'IL','attraction','Chicago Pier','https://s3.amazonaws.com/architecture-org/files/buildings/navy-pier-746.jpg');
insert into locations values('Chicago',7,'IL','hotel','Homewood Suites','https://media-cdn.tripadvisor.com/media/photo-p/0a/2d/e5/42/exterior.jpg');
insert into locations values('Chicago',8,'IL','restaurant','Bryanna''s Restaurant','https://static.wixstatic.com/media/fe968d_78bf619cba364362b971fc3c65d2f6c8~mv2.jpg/v1/fill/w_930,h_320,al_c,q_80,usm_0.66_1.00_0.01/fe968d_78bf619cba364362b971fc3c65d2f6c8~mv2.jpg');
insert into locations values('Detroit',9,'MI','city','Detroit','https://www.bridgemi.com/sites/default/files/hero_images/detroit_skyline.jpg');
insert into locations values('Detroit',10,'MI','attraction','Detroit Institute of Arts','https://www.trbimg.com/img-53c01f64/turbine/la-et-cm-detroit-institute-of-arts-20140711');
insert into locations values('Detroit',11,'MI','restaurant','Dilla''s Delights','https://cdn0.vox-cdn.com/thumbor/d8uXOm9KWzSQGUEKdGto2r6pcYE=/cdn0.vox-cdn.com/uploads/chorus_asset/file/6446449/Dillas-103.0.jpg');
insert into locations values('Detroit',12,'MI','hotel','MotorCity Casino Hotel','https://exp.cdn-hotels.com/hotels/2000000/1770000/1764800/1764738/a1449a73_z.jpg');
insert into locations values('Los Angeles',13,'CA','city','Los Angeles','https://www.fortunebuilders.com/wp-content/uploads/2016/04/downtown-los-angeles.jpg');
insert into locations values('Los Angeles',14,'CA','attraction','Venice Beach','https://1.bp.blogspot.com/-8z7d0CGy5U4/UFLB2TL3emI/AAAAAAAAPNg/66cOc5c9204/s1600/DSC_0832.jpg');
insert into locations values('Los Angeles',15,'CA','hotel','Hotel Indigo Los Angeles','');
insert into locations values('Los Angeles',16,'CA','restaurant','San Pedro Fish Market & Restaurant','https://ww1.prweb.com/prfiles/2015/11/30/13106792/LAnzate%20and%20shrimp%20trays.jpg');
